### ISSUE TITLE
intron end position exclusive ? 

### ISSUE THREAD

**Issue by lindenb** [nellore/intropolis#3]
Hi all,
the doc says that the 3rd column is:

```
intron end position (1-based; exclusive)
```

I'm looking at the line:

```
chr1    14830   14969   -   GT  AG 1,3,5,7,12,13,20,28,33,36,43,44,51,52,53,54,57,58,63,65,66,67
```

in the UCSC genome browser:

![jeter screen](https://cloud.githubusercontent.com/assets/33838/15325356/72dd3180-1c4a-11e6-993b-8ae6e3ca1677.jpg)

the introns clearly end 14969 **inclusive** , not exclusive (should be 14970) . Or did I miss something ?

Thank you for your help.

Pierre

**Comment by nellore** [comment]
True that. Fixed in 6693c72. Nice catch.
