### ISSUE TITLE
Can you add sample specific read counts?

### ISSUE THREAD

**Issue by Corvus7** [nellore/intropolis#4]
Hi,

It would be very useful if the data can be downloaded for each sample separately. I takes too much time to parse the file to get each individual dataset.

Thanks,

**Comment by nellore** [comment]
Check out our new tool recount (https://jhubiostatistics.shinyapps.io/recount/) for junctions by project, at least, and much more.

**Comment by lcolladotor** [comment]
Hi @Corvus7,

Have you had a change to look at `recount`? If so, did it solve this issue?

Best,
Leonardo

**Comment by Corvus7** [comment]
Hi @lcolladotor and @nellore 

I looked at recount. However, i could not figure out how to build a snaptron_query that will give me the below columns:
**chr junction_acceptor junction_donor strand acceptor_bases donor_bases sample sample_tissue number_of_reads**

May be you could have some more examples for building snaptron_queries? I dont want comma separated lists of read counts.

Thanks,

**Comment by lcolladotor** [comment]
Have you looked at the `rse_jx.Rdata` file for the particular project that you are interested in?

For example:

``` R
library('recount')
download_study('SRP009615', type = 'rse-jx')
load(file.path('SRP009615', 'rse_jx.Rdata'))
head(assay(rse_jx, 1))
rowRanges(rse_jx)
```

**Comment by Corvus7** [comment]
@lcolladotor 

Thank you. 
But i need this for all samples (~500 or so) of the cell lines and tissues that i am analysing. So i will make a list of all these accessions and individually pull it out with apply.

**Comment by lcolladotor** [comment]
Hi Corvus7,

Lets say that your ~500 samples are in 5 different SRA projects. Then you can download the `rse_jx` objects for all 5 projects, and keep the samples you are interested in. Even if it's a few SRA projects, this will probably be easier/faster than working with the Intropolis table.

Best,
Leonardo
