### ISSUE TITLE
Is there a mouse version?

### ISSUE THREAD

**Issue by xiaonalu** [nellore/intropolis#6]
Hi 
Is there a mouse version of the junctions? Thanks

**Comment by nellore** [comment]
Yes! Check out recount3 and snapcount at rna.recount.bio, or if you just want the junctions, http://snaptron.cs.jhu.edu/data/srav1m/.

**Comment by xiaonalu** [comment]
Thank you,
Actually, I want to use it as an input for SQANTI3, which said "Intropolis Junction BED file. In previous versions of SQANTI, it was provided a version of Intropolis for hg38 genome, modified into STAR junction format which is still valid." Do you mind guide me which file of the mouse in the "http://snaptron.cs.jhu.edu/data/srav1m/<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsnaptron.cs.jhu.edu%2Fdata%2Fsrav1m%2F&data=04%7C01%7Cxiaona.lu%40yale.edu%7C609d83e0169c41e277f808d979e4456e%7Cdd8cbebb21394df8b4114e3e87abeb5c%7C0%7C0%7C637674843609218838%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=966DeZFL3NzFY0GHPdMVUGnGKTyE8dNAJlgXQfQAeAU%3D&reserved=0>" equal to your human junction file? Thank you so much
Best
Xiaona
________________________________

**Comment by nellore** [comment]
There isn't, but you can make one! 1) Download http://snaptron.cs.jhu.edu/data/srav1m/junctions.bgz. 2) Use http://www.htslib.org/doc/bgzip.html to decompress it and obtain a TSV. 3) Field labels are as in Table 5 of http://snaptron.cs.jhu.edu/reftables.html. Reformat so field labels are as described in item A of the README at https://github.com/nellore/intropolis.

**Comment by xiaonalu** [comment]
Thank you~~~ I think I can make it following your detailed tutorial
Best
Xiaona
________________________________

**Comment by nellore** [comment]
Let us know if you have any more issues!

**Comment by xiaonalu** [comment]
Thank you,
I think I got the mouse junctions file now, while I guess it's based on mm10, could I change it to GRCm39? Thanks
Best
Xiaona
________________________________

**Comment by nellore** [comment]
A liftover should work on the vast majority of junctions. We did this from hg19 to hg38 way back when with https://github.com/nellore/runs/blob/master/sra/liftover_intropolis.py, as described in https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1118-6. The script should just work if you use an mm10-to-mm39 liftover chain instead of an hg19-to-hg38 liftover chain. Note the script calls UCSC's `liftover` executable with a specific choice of command-line parameters. You might decide that different ones are appropriate for a junction liftover.

**Comment by xiaonalu** [comment]
Hello,
Sorry for another question. I found in the mouse version junction file, the largest chromosome number is 28. Did I download a wrong file? Thanks
[cid:5d8cd49a-5bf0-44cb-81d2-c786825240a7]
Best
Xiaona
________________________________

**Comment by nellore** [comment]
Can you paste the full line?

**Comment by xiaonalu** [comment]
Could below or attached work? Thanks
Best
Xiaona

0       ERCC-00002      21      58      38      +       0       GC      AG      0       0       ,3599133:1      1       1       1.0     1       1
1       ERCC-00002      21      537     517     +       0       GC      AG      0       0       ,7200355:5      1       5       5.0     5       1
2       ERCC-00002      21      542     522     +       0       GC      AG      0       0       ,3410518:9,3453585:1,3457108:1,3478101:1        4       12      3.0     1.
0       1
3       ERCC-00002      27      85      59      +       0       GC      AG      0       0       ,2672789:1      1       1       1.0     1       1
4       ERCC-00002      28      92      65      -       0       CT      AC      0       0       ,1574011:2      1       2       2.0     2       1
5       ERCC-00002      28      304     277     -       0       CT      AC      0       0       ,3148371:1      1       1       1.0     1       1
6       ERCC-00002      28      381     354     -       0       CT      AC      0       0       ,2638963:1      1       1       1.0     1       1
7       ERCC-00002      28      442     415     -       0       CT      AC      0       0       ,1531966:1,1537183:6,3076152:1,1540623:1,6032690:2,6050019:1,6051003:4,607
9724:1,6082167:4,6082678:1,6115449:2,6097192:1,6097467:1,6130789:7,6134891:1,6036583:22,6135408:11,6102634:8,6145081:1,6180264:1,1730717:4,1730845:1,3442932:1,3453109:1,3
483703:2,1769516:1,3564856:1,3589661:1,7178530:1,889165:5,889221:4,889229:5,893884:6,893892:6,893901:7,893956:11,2639124:1,2639154:1,2681936:1,2682160:1,2683475:1,2695186
:1,2821716:1,2828091:2  44      143     3.25    1.0     1
8       ERCC-00002      28      454     427     -       0       CT      AC      0       0       ,6162985:1      1       1       1.0     1       1

________________________________

**Comment by nellore** [comment]
`ERCC-00002` is a spike-in included among the set of contigs to which we aligned; see https://www.thermofisher.com/order/catalog/product/4456740#/4456740. You likely care about the contigs with these names: http://hgdownload.cse.ucsc.edu/goldenpath/mm10/bigZips/mm10.chrom.sizes.

**Comment by xiaonalu** [comment]
Thank you.
Is it still possible to generate a junction file for mice using this tsv? Thanks
Best
Xiaona
________________________________

**Comment by nellore** [comment]
http://snaptron.cs.jhu.edu/data/srav1m/junctions.bgz has junctions in `mm10` coordinates from mouse samples across SRA, but it also includes junctions detected in alignments to spike-ins, which you can ignore.

I may be misunderstanding what you want, though! If so, can you be as specific as possible in a clarification? Thanks!

**Comment by xiaonalu** [comment]
Hi,
I want an input for SQANTI3. It provides a human version of "Intropolis Junction BED file". I need a similar document, but for mice.
Could I just remove the spike-ins, and use the rest of the tsv? Thanks a lot
Best
Xiaona
________________________________

**Comment by nellore** [comment]
You can remove spike-ins and use the rest of the TSV, yes, though you'll have to reformat the file so it is a BED. All the information you need is contained in the TSV though! See my 3-step comment above.

**Comment by xiaonalu** [comment]
Got it. Thank you so much
Best
Xiaona
________________________________
